### ISSUE TITLE
Improve documentation for native-encryption

### ISSUE THREAD

**Issue by ghost** [a-schaefers/themelios#3]
I hosed my system once trying to puzzle out how to get native encryption enabled for $HOME.

What I did the first time:
```
# Upgrade pool
zfs upgrade -a
# Destroy home dataset
zpool destroy zroot/HOME/home
# Create dataset
zfs create -o encryption=on -o keyformat=passphrase zroot/HOME/home
```
resulted in an unbootable system.

I checked themelios the program and figured I ought to do the last invocation this way:
`zfs create -o mountpoint=legacy -o canmount=on -o encryption=on -o keyformat=passphrase zroot/HOME/home`
which worked.

Now I have an encrypted $HOME on ZFS and I couldn't be happier.

**Comment by a-schaefers** [comment]
Awesome I couldn't remember how I did it. If you can make a pr I'd be happy to accept it.

**Comment by a-schaefers** [comment]
Oh hey by the way @Spass1966 , you may need to ensure that zfs get com.sun:auto-snapshot shows it is active for your newly re-created zroot/HOME/home dataset if you intended to use the autosnapshot service. You could set it back to true for the new dataset by doing 

zfs set com.sun:auto-snapshot=true zroot/HOME/home

**Comment by ghost** [comment]
I did so, thank you! I also `sudo zpool set autotrim=on zroot`, another new feature that's great for my SSD.
